spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: 3600000
  refresh-token-validity: 604800000