spring:
  config:
    import:
      - "aws-parameterstore:/config/common/"
      - "aws-parameterstore:/config/dev/"

  datasource:
    url: jdbc:mysql://${db.host}:${db.port:3306}/${db.name}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    display-request-duration: true
    tryItOutEnabled: true

# Logging 설정 (Loki로 전송)
logging:
  file:
    name: /app-logs/application.log
    max-size: 100MB
    max-history: 7
    total-size-cap: 1GB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

cors:
  allowed-origins: >
    http://dev.golfrental.com,
    http://13.209.84.23:3000,
    https://golfrental-sepia.vercel.app